# Generated by Django 6.0.1 on 2026-02-12 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0001_initial'),
        ('users', '0003_user_tenant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userrole',
            name='tenant',
            field=models.ForeignKey(default='f1dfc4c2-1f9d-4b30-9455-c813fa420297', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_user_roles', to='context.tenant'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'tenant', 'role')},
        ),
    ]
