# Generated by Django 6.0.1 on 2026-02-11 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0001_initial'),
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tenant',
            field=models.ForeignKey(default='f1dfc4c2-1f9d-4b30-9455-c813fa420297', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='context.tenant'),
            preserve_default=False,
        ),
    ]
