# Generated by Django 6.0.1 on 2026-03-01 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('context', '0001_initial'),
        ('core_api', '0001_initial'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boards_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='board',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boards_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='board',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='context.tenant'),
        ),
        migrations.AddField(
            model_name='boardstatus',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='core_api.board'),
        ),
        migrations.AddField(
            model_name='division',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divisions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='division',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='context.tenant'),
        ),
        migrations.AddField(
            model_name='board',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='core_api.division'),
        ),
        migrations.AddField(
            model_name='divisionmember',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core_api.division'),
        ),
        migrations.AddField(
            model_name='divisionmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='section',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='section',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core_api.division'),
        ),
        migrations.AddField(
            model_name='section',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='context.tenant'),
        ),
        migrations.AddField(
            model_name='board',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='core_api.section'),
        ),
        migrations.AddField(
            model_name='task',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core_api.board'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Set this to make the task a subtask of another task.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='core_api.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='workflows.workflowstage'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core_api.boardstatus'),
        ),
        migrations.AddField(
            model_name='task',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='context.tenant'),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='workflows.workflow'),
        ),
        migrations.AddField(
            model_name='taskassignee',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskassignee',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.task'),
        ),
        migrations.AddField(
            model_name='taskassignee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='tasks_assigned', through='core_api.TaskAssignee', through_fields=('task', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core_api.task'),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_attachments', to='context.tenant'),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core_api.taskcomment'),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core_api.task'),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to='context.tenant'),
        ),
        migrations.AddField(
            model_name='taskdependency',
            name='blocker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking', to='core_api.task'),
        ),
        migrations.AddField(
            model_name='taskdependency',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskdependency',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='core_api.task'),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_history_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core_api.task'),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_history', to='context.tenant'),
        ),
        migrations.AddIndex(
            model_name='boardstatus',
            index=models.Index(fields=['board', 'order'], name='core_api_bo_board_i_a10de9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='boardstatus',
            unique_together={('board', 'name')},
        ),
        migrations.AddIndex(
            model_name='division',
            index=models.Index(fields=['tenant', 'is_deleted'], name='core_api_di_tenant__e46e4b_idx'),
        ),
        migrations.AddIndex(
            model_name='division',
            index=models.Index(fields=['tenant', 'slug'], name='core_api_di_tenant__41d03a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='division',
            unique_together={('tenant', 'slug')},
        ),
        migrations.AddIndex(
            model_name='divisionmember',
            index=models.Index(fields=['division', 'role'], name='core_api_di_divisio_e85424_idx'),
        ),
        migrations.AddIndex(
            model_name='divisionmember',
            index=models.Index(fields=['user'], name='core_api_di_user_id_249a96_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='divisionmember',
            unique_together={('division', 'user')},
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['tenant', 'division'], name='core_api_se_tenant__5c1e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['division', 'is_deleted'], name='core_api_se_divisio_012485_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('division', 'slug')},
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['tenant', 'is_deleted'], name='core_api_bo_tenant__7f2d65_idx'),
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['division'], name='core_api_bo_divisio_a0ed8a_idx'),
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['section'], name='core_api_bo_section_6dde31_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignee',
            index=models.Index(fields=['task'], name='core_api_ta_task_id_cd50bb_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignee',
            index=models.Index(fields=['user'], name='core_api_ta_user_id_268868_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskassignee',
            unique_together={('task', 'user')},
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant', '-created_at'], name='core_api_ta_tenant__3d2a26_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant', 'is_deleted'], name='core_api_ta_tenant__737da2_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant', 'due_date'], name='core_api_ta_tenant__c60950_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant', 'ref_id'], name='core_api_ta_tenant__21471d_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['board', 'order'], name='core_api_ta_board_i_b5e755_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['parent'], name='core_api_ta_parent__a5d210_idx'),
        ),
        migrations.AddIndex(
            model_name='taskattachment',
            index=models.Index(fields=['tenant', 'task'], name='core_api_ta_tenant__d4c946_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['task', 'created_at'], name='core_api_ta_task_id_33d834_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['parent'], name='core_api_ta_parent__cc72bd_idx'),
        ),
        migrations.AddIndex(
            model_name='taskdependency',
            index=models.Index(fields=['task'], name='core_api_ta_task_id_bfd18b_idx'),
        ),
        migrations.AddIndex(
            model_name='taskdependency',
            index=models.Index(fields=['blocker'], name='core_api_ta_blocker_918db8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskdependency',
            unique_together={('task', 'blocker')},
        ),
        migrations.AddIndex(
            model_name='taskhistory',
            index=models.Index(fields=['tenant', 'task'], name='core_api_ta_tenant__02c594_idx'),
        ),
        migrations.AddIndex(
            model_name='taskhistory',
            index=models.Index(fields=['timestamp'], name='core_api_ta_timesta_9ae86f_idx'),
        ),
    ]
