# Generated by Django 6.0.1 on 2026-03-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='default_permission',
            field=models.CharField(choices=[('FULL_EDIT', 'Full edit'), ('COMMENT_ONLY', 'Comment only'), ('VIEW_ONLY', 'View only')], default='FULL_EDIT', max_length=20),
        ),
        migrations.AddField(
            model_name='division',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
