# Generated by Django 6.0.1 on 2026-02-12 06:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0001_initial'),
        ('core_api', '0003_task_core_api_ta_tenant__1f5f49_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='core_api_ta_tenant__1f5f49_idx',
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant', '-created_at'], name='core_api_ta_tenant__3d2a26_idx'),
        ),
    ]
