# Generated by Django 6.0.1 on 2026-03-02 07:22

import django.db.models.deletion
from django.db import migrations, models


def backfill_task_division(apps, schema_editor):
    Task = apps.get_model("core_api", "Task")
    for task in Task.objects.filter(board__isnull=False).select_related(
        "board", "board__section"
    ):
        board = task.board
        division_id = board.division_id
        if division_id is None and board.section_id:
            division_id = board.section.division_id
        if division_id and task.division_id != division_id:
            task.division_id = division_id
            task.save(update_fields=["division"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0003_division_default_permission_division_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core_api.division'),
        ),
        migrations.RunPython(backfill_task_division, noop_reverse),
    ]
