# Generated by Django 6.0.1 on 2026-03-02 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0001_initial'),
        ('core_api', '0004_task_division'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['division'], name='core_api_ta_divisio_1676b6_idx'),
        ),
    ]
