# Generated by Django 6.0.1 on 2026-03-03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0001_initial'),
        ('core_api', '0005_task_core_api_ta_divisio_1676b6_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FILE', 'File'), ('TEXT', 'Text'), ('URL', 'Url')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='task_proofs/%Y/%m/')),
                ('text', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_task_proofs', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='core_api.task')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_proofs', to='context.tenant')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='taskproof',
            index=models.Index(fields=['tenant', 'task'], name='core_api_ta_tenant__68e06c_idx'),
        ),
        migrations.AddIndex(
            model_name='taskproof',
            index=models.Index(fields=['task', 'type'], name='core_api_ta_task_id_7f8f50_idx'),
        ),
    ]
