# Generated by Django 6.0.1 on 2026-03-07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("context", "0001_initial"),
        ("core_api", "0006_taskproof"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("TASK_ASSIGNED", "Task Assigned"), ("TASK_STATUS_CHANGED", "Task Status Changed"), ("TASK_PROOF_SUBMITTED", "Task Proof Submitted"), ("TASK_COMPLETED", "Task Completed")], max_length=32)),
                ("title", models.CharField(max_length=160)),
                ("body", models.CharField(blank=True, max_length=255)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="notifications_triggered", to=settings.AUTH_USER_MODEL)),
                ("task", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to="core_api.task")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to="context.tenant")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["tenant", "user", "is_read"], name="core_api_not_tenant__bd6548_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["tenant", "user", "-created_at"], name="core_api_not_tenant__16d51b_idx"),
        ),
    ]
