# Generated by Django 6.0.1 on 2026-02-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0008_taskhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
