# Generated by Django 6.0.1 on 2026-02-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0010_taskattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='blocked_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('P1', 'Critical'), ('P2', 'High'), ('P3', 'Normal'), ('P4', 'Low')], default='P3', max_length=2),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='priority',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('BLOCKED', 'Blocked'), ('WAITING', 'Waiting'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='NOT_STARTED', max_length=32),
        ),
    ]
