# Generated by Django 6.0.1 on 2026-02-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0012_alter_task_due_date_alter_taskhistory_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
