# Generated by Django 6.0.1 on 2026-02-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0013_alter_task_title_alter_taskhistory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('BLOCKED', 'Blocked'), ('WAITING_REVIEW', 'Waiting Review'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='NOT_STARTED', max_length=32),
        ),
    ]
