# Generated by Django 6.0.1 on 2026-02-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0014_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('SOFT_DELETED', 'Soft Deleted'), ('SUBMITTED', 'Submitted for Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=32),
        ),
    ]
