# Generated by Django 6.0.1 on 2026-02-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0015_alter_taskhistory_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskattachment',
            name='type',
            field=models.CharField(choices=[('REQUIREMENT', 'Requirement'), ('SUBMISSION', 'Submission')], default='REQUIREMENT', max_length=20),
        ),
    ]
