# Generated by Django 6.0.1 on 2026-03-01 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('context', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=40)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('color', models.CharField(default='blue', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_default', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='context.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowPresetStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('order', models.PositiveIntegerField()),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='workflows.workflowpreset')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowPresetWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField()),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='workflows.workflowpreset')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('order', models.PositiveIntegerField()),
                ('is_terminal', models.BooleanField(default=False)),
                ('requires_attachments', models.BooleanField(default=False)),
                ('requires_approval', models.BooleanField(default=False)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='workflows.workflow')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_role', models.CharField(max_length=32)),
                ('from_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to='workflows.workflowstage')),
                ('to_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='workflows.workflowstage')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='workflows.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Dashboard', max_length=120)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private'), ('INTERNAL', 'Shared Internal'), ('PUBLIC', 'Public Link')], default='INTERNAL', max_length=20)),
                ('is_default', models.BooleanField(default=True)),
                ('global_filters', models.JSONField(blank=True, default=dict)),
                ('widgets', models.JSONField(blank=True, default=list)),
                ('auto_refresh_seconds', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_dashboards', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_configs', to='context.tenant')),
            ],
            options={
                'ordering': ['name', '-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_dashboard_name_per_tenant'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('tenant',), name='uniq_default_dashboard_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='TenantModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_states', to='workflows.moduledefinition')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_modules', to='context.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'module'), name='uniq_tenant_module')],
            },
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_workflow_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('tenant',), name='uniq_default_workflow_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='workflowpresetstage',
            constraint=models.UniqueConstraint(fields=('preset', 'name'), name='uniq_preset_stage_name'),
        ),
        migrations.AddConstraint(
            model_name='workflowpresetstage',
            constraint=models.UniqueConstraint(fields=('preset', 'order'), name='uniq_preset_stage_order'),
        ),
        migrations.AddConstraint(
            model_name='workflowpresetwidget',
            constraint=models.UniqueConstraint(fields=('preset', 'name'), name='uniq_preset_widget_name'),
        ),
        migrations.AddConstraint(
            model_name='workflowpresetwidget',
            constraint=models.UniqueConstraint(fields=('preset', 'order'), name='uniq_preset_widget_order'),
        ),
        migrations.AddConstraint(
            model_name='workflowstage',
            constraint=models.UniqueConstraint(fields=('workflow', 'name'), name='uniq_stage_name_per_workflow'),
        ),
        migrations.AddConstraint(
            model_name='workflowstage',
            constraint=models.UniqueConstraint(fields=('workflow', 'order'), name='uniq_stage_order_per_workflow'),
        ),
        migrations.AddConstraint(
            model_name='workflowtransition',
            constraint=models.UniqueConstraint(fields=('workflow', 'from_stage', 'to_stage', 'allowed_role'), name='uniq_transition_per_role'),
        ),
    ]
