# Generated by Django 6.0.1 on 2026-03-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_terminal', models.BooleanField(default=False)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='workflows.workflow')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TransitionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_roles', models.JSONField(blank=True, default=list)),
                ('from_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_rules', to='workflows.workflowstatus')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_rules', to='workflows.workflowstatus')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_rules', to='workflows.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='ProofRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FILE', 'File'), ('TEXT', 'Text'), ('URL', 'Url')], max_length=10)),
                ('label', models.CharField(max_length=255)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('transition_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_requirements', to='workflows.transitionrule')),
            ],
        ),
        migrations.AddConstraint(
            model_name='workflowstatus',
            constraint=models.UniqueConstraint(fields=('workflow', 'name'), name='uniq_status_name_per_workflow'),
        ),
        migrations.AddConstraint(
            model_name='workflowstatus',
            constraint=models.UniqueConstraint(fields=('workflow', 'order'), name='uniq_status_order_per_workflow'),
        ),
        migrations.AddConstraint(
            model_name='transitionrule',
            constraint=models.UniqueConstraint(fields=('workflow', 'from_status', 'to_status'), name='uniq_transition_rule_per_status_pair'),
        ),
        migrations.AddIndex(
            model_name='proofrequirement',
            index=models.Index(fields=['transition_rule', 'is_mandatory'], name='workflows_p_transit_ed2c7f_idx'),
        ),
    ]
