# Generated by Django 6.0.1 on 2026-02-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstage',
            name='requires_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='requires_attachments',
            field=models.BooleanField(default=False),
        ),
    ]
