# Generated by Django 6.0.1 on 2026-03-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0002_workflowstatus_transitionrule_proofrequirement"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstage",
            name="color",
            field=models.CharField(default="#6B7280", max_length=7),
        ),
        migrations.AddField(
            model_name="workflowstatus",
            name="color",
            field=models.CharField(default="#6B7280", max_length=7),
        ),
    ]
