# Generated by Django 6.0.1 on 2026-02-23 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0001_initial'),
        ('workflows', '0002_workflowstage_requires_approval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=40)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('color', models.CharField(default='blue', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TenantModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_states', to='workflows.moduledefinition')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_modules', to='context.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'module'), name='uniq_tenant_module')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowPresetStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('order', models.PositiveIntegerField()),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='workflows.workflowpreset')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('preset', 'name'), name='uniq_preset_stage_name'), models.UniqueConstraint(fields=('preset', 'order'), name='uniq_preset_stage_order')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowPresetWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField()),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='workflows.workflowpreset')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('preset', 'name'), name='uniq_preset_widget_name'), models.UniqueConstraint(fields=('preset', 'order'), name='uniq_preset_widget_order')],
            },
        ),
    ]
