# Generated by Django 6.0.1 on 2026-02-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0003_moduledefinition_workflowpreset_tenantmodule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workflow",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workflow",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]

