# Generated by Django 6.0.1 on 2026-02-24 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("context", "0001_initial"),
        ("workflows", "0004_workflow_publish_state_and_version"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="Dashboard", max_length=120)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("PRIVATE", "Private"),
                            ("INTERNAL", "Shared Internal"),
                            ("PUBLIC", "Public Link"),
                        ],
                        default="INTERNAL",
                        max_length=20,
                    ),
                ),
                ("is_default", models.BooleanField(default=True)),
                ("global_filters", models.JSONField(blank=True, default=dict)),
                ("widgets", models.JSONField(blank=True, default=list)),
                ("auto_refresh_seconds", models.PositiveIntegerField(default=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_configs",
                        to="context.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "-updated_at"],
                "constraints": [
                    models.UniqueConstraint(fields=("tenant", "name"), name="uniq_dashboard_name_per_tenant"),
                    models.UniqueConstraint(
                        condition=Q(("is_default", True)),
                        fields=("tenant",),
                        name="uniq_default_dashboard_per_tenant",
                    ),
                ],
            },
        ),
    ]
